### ISSUE TITLE
make standalone_snapshot needs to wait after async device detach request

### ISSUE THREAD

**Issue by jistr** [openstack-k8s-operators/data-plane-adoption#103]
The device detach before snapshot [1] is asynchronous and if it doesn't complete by the time the snapshot command is executed, the snapshotting will fail. We should insert `sleep 3` between these two. Since the snapshot is being taken very infrequently, adding the 3 seconds should be fine and we don't need to look for more complex and exact methods of detecting when the detach has finished.

[1] https://github.com/openstack-k8s-operators/install_yamls/blob/cd28ad73a8e0966e97f1b8bcd044c2998be47767/devsetup/Makefile#L189

**Comment by karelyatin** [comment]
IIUC this fixing below error, right?
$ make standalone_snapshot                                                                               
virsh --connect=qemu:///system detach-device-alias edpm-compute-0 fs0 --live || true
Device detach request sent successfully                                                                                                 
                                                                    
virsh --connect=qemu:///system snapshot-create-as --atomic --domain edpm-compute-0 --name clean
error: Requested operation is not valid: migration with virtiofs device is not supported
