### ISSUE TITLE
Post cinder adoption, volume creation failing with  _DEFAULT_  volume type

### ISSUE THREAD

**Issue by archana203** [openstack-k8s-operators/data-plane-adoption#112]
During cinder adoption [](https://openstack-k8s-operators.github.io/data-plane-adoption/openstack/cinder_adoption/
) we are passing default_volume_type=tripleo in customServiceConfig section of CinderApi service but the configuration is not reflected in cinder service pods and volume creation failed with following message :-

[ospng@dell-r640-089 osp2]$ openstack volume create --image cirros --bootable --size 1 disk_new
The request cannot be fulfilled as the default volume type __DEFAULT__ cannot be found. (HTTP 500) (Request-ID: req-621e986d-7220-474b-aaa2-5282a49f866c)
command terminated with exit code 1

**Comment by Akrog** [comment]
We have merged PR#250 in the cinder-operator, so this bug should have been fixed.
