### ISSUE TITLE
Improve Development environment docs by making explicit which commands should run on host/VM

### ISSUE THREAD

**Issue by fao89** [openstack-k8s-operators/data-plane-adoption#114]
The following section should be executed inside the standalone node:
https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/docs/contributing/development_environment.md#create-a-workload-to-adopt
`ssh -i ~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100`

**Comment by jistr** [comment]
This is a duplicate of #133. This one came earlier but i'd leave #133 open as it goes into more depth about the problem that we hit during the hackathon.
