### ISSUE TITLE
"sudo cephadm shell" command in dev env setup needs to be run from the standalone VM

### ISSUE THREAD

**Issue by jistr** [openstack-k8s-operators/data-plane-adoption#133]
Instead of
```
sudo cephadm shell -- rbd -p images ls -l
```

we should have
```
ssh -i ~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100 sudo cephadm shell -- rbd -p images ls -l
```

Or we can perhaps drop the command from there entirely because it's a "just in case" check that we haven't seen fail yet.

**Comment by matbu** [comment]
https://github.com/openstack-k8s-operators/data-plane-adoption/pull/161
