### ISSUE TITLE
cinder-cfg.py generating invalid config

### ISSUE THREAD

**Issue by jistr** [openstack-k8s-operators/data-plane-adoption#138]
We hit two issues with the cinder-cfg.py generated config:

* the serviceUser is meant to be a string rather than a list.

* the cinderVolumes section is invalid.

@karelyatin noticed that the problem with the the cinderVolumes section was incorrect networkAttachments nesting (under cinderVolumes rather than under tripleo-ceph).

After correcting these issues, Cinder seems to deploy but the cinder-volume pod is restarting.

**Comment by Akrog** [comment]
I have fixed those 2 issues in PR#139 and I'm wondering if the restart is related to the missing `extraVolumes` section.

One of the patches of the PR fixes the `extraVolumes` sample not getting rendered for RBD backends.
