### ISSUE TITLE
[Glance adoption] Wrong config reference used

### ISSUE THREAD

**Issue by karelyatin** [openstack-k8s-operators/data-plane-adoption#147]
oc exec -t $GLANCE_POD -c glance-api -- cat /etc/glance/glance.conf.d/02-global.conf  --> oc exec -t $GLANCE_POD -c glance-api -- cat /etc/glance/glance.conf.d/02-config.conf

Reference https://github.com/openstack-k8s-operators/glance-operator/commit/7529745b87f07d4c5616e4a80f7aeace10dadbb5

**Comment by matbu** [comment]
https://github.com/openstack-k8s-operators/data-plane-adoption/pull/160

**Comment by jistr** [comment]
Fix merged, thanks!
